### ISSUE TITLE
Transfer to RU CMS

### ISSUE THREAD

**Issue by ihuijsmans** [Donders-Institute/rdm-wiki#36]
Start transfer Users' Guide

**Comment by ihuijsmans** [comment]
Start transfer Users' Guide : WebDav login

**Comment by ihuijsmans** [comment]
Start transfer Users' Guide: Your user account

**Comment by ihuijsmans** [comment]
Start transfer FAQ
Start transfer protocols (as pfd with bookmarks)

**Comment by robertoostenveld** [comment]
if I am correct, all planned documents have been transferred, right?

If so, please close this issue.
