### ISSUE TITLE
make a list of definitions

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/rdm-wiki#38]
what do the following abbreviations or words mean?

rdm
dac
rdc
dsc
modality
session
subject
project
ppm

etc.

**Comment by ihuijsmans** [comment]
details
author
role
collection
collection type
SURFconext
Organisational unit
Onegini
trusted identity provider

**Comment by robertoostenveld** [comment]
metadata
attributes
sfn
mesh
surf
ou (see previous comment)
idp (=identity provider)

**Comment by robertoostenveld** [comment]
preprint - A preprint is a complete and public draft of a scientific document. Preprints are often intended to be submitted to journals for peer-review and subsequent publication.  However, they are public and permanent in a way that journal submissions under review are not. 

This is from http://grants.nih.gov/grants/rfi/rfi.cfm?ID=60

**Comment by robertoostenveld** [comment]
PMCID - The PubMed Central reference number (PMCID) links to full-text papers in PubMed Central. This is different from the PMID, which links to abstracts in PubMed.

**Comment by robertoostenveld** [comment]
PMID
handle
doi
pubmed

**Comment by robertoostenveld** [comment]
@EricMaris @hurngchunlee @katrinsutter @xiaochenzheng here is the list of terms that was just mentioned.

**Comment by robertoostenveld** [comment]
... and that we should avoid ;-)

**Comment by robertoostenveld** [comment]
@ihuijsmans and @EricMaris, this is a TODO item from half a year ago. Do we still want to provide a list of abbreviations and terms in the documentation? If not, then this issue is to be closed.

**Comment by robertoostenveld** [comment]
over email besproken, niet meer nodig.
