### ISSUE TITLE
DAC_3011020.09_511 needs some work (MOUS)

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/rdm-wiki#49]
This one is empty. There will not be any data recorded in the project any more. I think it would be better to delete it. I'll discuss with @schoffelen.

**Comment by robertoostenveld** [comment]
@schoffelen, is it needed (desired) to have anything else besides a DSC (data sharing collection) for MOUS? I suppose that the raw data is all nicely archived on USB disks.

**Comment by schoffelen** [comment]
No, DSC only would be fine. I would assume that the 'low-level' reorganization (before uploading it onto the RDM-system) takes place on the fileserver / qnap anyhow.

**Comment by robertoostenveld** [comment]
correct. 

@hurngchunlee can you delete it?

**Comment by hurngchunlee** [comment]
done
