### ISSUE TITLE
atribute for the location for non-digital data

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/rdm-wiki#7]
TBD: We still need an attributes for the location of the non-digital data. I propose to add a repeatable free-text attribute: locationNonDigitalRoom.

**Comment by robertoostenveld** [comment]
this is not a topic relating to documentation, but to the implementation of the AUV triplets in irons. The end user would not care.

**Comment by hurngchunlee** [comment]
I recalled a discussion long time ago: How to document non-digital data?  ... and one possible approach is that the user make a digital file (e.g. text file or spreadsheet) with content describing the location of non-digital data, and upload this file into a collection.

Is it still considered as a reasonable approach?

**Comment by EricMaris** [comment]
In its extreme form (no location attribute and all info in a file) this will bring us into problems over time: (1)  individual researchers are totally free to put anything in those files, and (2) the repository offers no way to search for this location information in case it has to be updated (the content of one room is moved to another room).

I propose to specify the room as a collection attribution, and the location within the room in a file. If we have the room as an attribute, we can at least search for it.

I will discuss this with my DCN_m/s colleagues (Nael, Mike, Tansu, ...) who are the ones that bring in this type of data.

To be continued.

**Comment by robertoostenveld** [comment]
At the DCCN we also have saliva and blood samples and filled-out paper forms.

**Comment by robertoostenveld** [comment]
@EricMaris has there been any progress on this? If not, I suggest we treat it as a documentation-only issue.

**Comment by robertoostenveld** [comment]
@EricMaris has there been any progress on this? If not, I suggest we treat it as a documentation-only issue.

**Comment by robertoostenveld** [comment]
since there is no progress on this, I'll close the issue.
